user_input = input("Enter your text: ")
find = user_input.replace("a","4")
find = find.replace("b","8")
find = find.replace("e","3")
find = find.replace("l","1")
find = find.replace("o","0")
find = find.replace("s","5")
find = find.replace("t","7")
print(find)